language: node_js
node_js:
  - "10"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_script:
   - npm install -g --silent @angular/cli

script:
  - npm run lint
  - ng build --prod --base-href https://iamjigz.github.io/bigoutsource/

notifications:
  email:
    on_failure: change
    on_success: change

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bigoutsource
  on:
    branch: master
