language: node_js
node_js:
  - 8.9

dist: trusty
sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_script:
   - npm install
   - npm install -g angular-cli-ghpages

script:
  - npm run lint
  # - ng build --prod --base-href /
  - ng build --prod --base-href https://iamjigz.github.io/bigoutsource/

notifications:
  email:
    on_failure: change
    on_success: change

after_success:
  - ngh --dir dist/garryphoto --no-silent

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   local_dir: dist/bigoutsource
#   on:
#     branch: master
